language: python

dist: xenial

python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install pytest codecov
  - pip install -e .[test]

script:
  - coverage run --source=powerdata_download -m pytest

after_success:
  - codecov

notifications:
  email: false
